###
GET http://localhost:8080/SA-Lab2-1.0-SNAPSHOT/api/warehouse/allproducts

###
GET http://localhost:8080/SA-Lab2-1.0-SNAPSHOT/api/warehouse/product/ads

###
GET http://localhost:8080/SA-Lab2-1.0-SNAPSHOT/api/warehouse/products/MEATS

###
POST http://localhost:8080/SA-Lab2-1.0-SNAPSHOT/api/warehouse/addproduct
Content-Type: Application/json

{
  "id": 1,
  "name": "",
  "category": "FRUITS",
  "rating": 9
}
